module.exports ={
    "AAA"  : "The Agricultural Adjustment Act.",
    "AAI"  : "Airports Authority of India.",
    "ABC"  : "American Broadcasting Company.",
    "AIDA" : "Attention, Interest, Desire, Action.",
    "AJAX" : "Asynchronous JavaScript and XML.",
    "AOV " : "Average Order Value.",
    "API"  : "Application Program Interface.",
    "AR"   : "Augmented Reality.",
    "ASO"  : "Application Store Optimization.",
    "ASP"  : "Application Service Provider.",
    "ATD"  : "Agency Trading Desk.",
    "B2B"  : "Business To Business.",
    "B2C"  : "Business To Consumer.",
    "BANT" : "Budget, Authority, Need, Time line.",
    "BEE"  : "Bureau of Energy Efficiency.",
    "BCCI" : "Board of Cricket Control in India.",
    "BJP"  : "Bharatiya Janata Party.",
    "CAN-SPAM": "Controlling the Assault of Non-Solicited Pornography And Marketing.",
    "CASL" : "Canadian Anti-Spam Legislation.",
    "CBI"  : "Central Bureau of Investigation.",
    "CBSE" : "Central Board of Secondary Education.",
    "CCC"  : "The Civilian Conservation Corps.",
    "CEO"  : "Chief Executive Officer.",
    "CGI"  : "Common Gateway Interface.",
    "CLV"  : "Customer Lifetime Value.",
    "CMS"  : "Content Management System.",
    "COMPUTER": "Common Operating Machine Particularly Used for Trade, Education, and Research.",
    "COS"  : "Content Optimization System.",
    "CPA"  : "Cost Per Action.",
    "CPC"  : "Cost Per Click.",
    "CPCB" : "Central Pollution Control Board.",
    "CPCV" : "Cost Per Completed View.",
    "CPD"  : "Cost Per Download.",
    "CPE"  : "Cost Per Engagement.",
    "CPI"  : "Cost Per Install.",
    "CPI"  : "Communist Party of India.",
    "CPL"  : "Cost Per Lead.",
    "CPM"  : "Cost Per Thousand.",
    "CPR"  : "Cost Per Registration.",
    "CPS"  : "Cost Per Subscription.",
    "CPV"  : "Cost Per View.",
    "CPWD" : "Central Public Works Department.",
    "CTA"  : "Call to Action.",
    "CR"   : "Conversion Rate.",
    "CRM"  : "Customer Relationship Management.",
    "CRO"  : "Conversion Rate Optimization.",
    "CSS"  : "Cascading Style Sheets.",
    "CTA"  : "Call To Action.",
    "CTR"  : "Click-Through Rate.",
    "CWA"  : "The Civil Works Administration.",
    "CX"   : "Customer Experience.",
    "DM"   : "Direct Mail.",
    "DMP"  : "Data Management Platform.",
    "DNS"  : "Domain Name System.",
    "DoT"  : "Department of Telecommunications.",
    "DR"   : "Direct Response.",
    "DSP"  : "Demand-Side Platform.",
    "EDN"  : "Electronic Distribution Network.",
    "ECPM" : "Effective CPM.",
    "EIA"  : "Environmental Impact Assessment.",
    "EPC"  : "Earnings Per Click.",
    "EPM"  : "Earnings Per Thousand.",
    "ESP"  : "Email Service Provider.",
    "FB"   : "Facebook.",
    "FBML" : "Facebook Markup Language.",
    "FDI"  : "Foreign Direct Investment.",
    "FDIC" : "The Federal Deposit Insurance Corp.",
    "FHA"  : "The Federal Housing Administration.",
    "FTP"  : "File Transfer Protocol.",
    "GA"   : "Google Analytics.",
    "GIF"  : "Graphics Interchange Format.",
    "GNU"  : "GNU's Not Unix.",
    "GPS"  : "Global Positioning System.",
    "GUI"  : "Graphical User Interface.",
    "HIPPO": "Highest Paid Person's Opinion.",
    "HTML" : "HyperText Markup Language.",
    "HTTP" : "Hyper Text Transfer Protocol.",
    "HTTPS": "Hyper Text Transfer Protocol Secure.",
    "IAF"  : "Indian Air Force.",
    "IGNOU": "Indira Gandhi National Open University.",
    "IIT"  : "Indian Institute of Technology.",
    "IM"   : "Instant Messaging.",
    "IMD"  : "India Meteorological Department.",
    "IMAP" : "Internet Message Access Protocol.",
    "INSAT": "Indian National Satellite.",
    "IP"   : "Intellectual property.",
    "IP"   : "Internet Protocol.",
    "IPTV" : "Internet Protocol Television.",
    "IRS"  : "Indian Remote Sensing Satellite.",
    "ISP"  : "Internet Service Provider.",
    "ISPF" : "Interactive System Productivity Facility.",
    "ISR"  : "Interrupt Service Routine.",
    "ISRO" : "Indian Space Research Organization.",
    "JSON" : "JavaScript Object Notation.",
    "JSP"  : "Jackson Structured Programming.",
    "KPI"  : "Key Performance Indicator.",
    "LAMP" : "Linux Apache MySQL Perl/Php/Python.",
    "LOC"  : "Line of Control.",
    "LTV"  : "Lifetime Value.",
    "LP"   : "Landing Page.",
    "MEA"  : "Ministry of External Affairs.",
    "MoM"  : "Month On Month.",
    "MLM"  : "Multi-level Marketing.",
    "MTD"  : "Month to Date.",
    "MRR"  : "Monthly Recurring Revenue.",
    "MVC"  : "Model View Controller.",
    "MVT"  : "Multivariate Testing.",
    "MVP"  : "Most Valuable Professional.",
    "NCSA" : "National Center for Supercomputing Applications.",
    "NDIS" : "Network Driver Interface Specification.",
    "NBC"  : "National Broadcasting Company.",
    "NGO's": "Non-Governmental Organisations.",
    "NPS"  : "Net Promoter Score.",
    "NRA"  : "The National Recovery Administration.",
    "OEM"  : "Original Equipment Manufacturer.",
    "ONGC" : "Oil and Natural Gas Commission.",
    "OS"   : "Operating System.", 
    "PAN"  : "Permanent Account Number.",
    "PERL" : "Practical Extraction and Report Language.", 
    "PBS"  : "Public Broadcasting Service.",
    "PHP"  : "PHP Hypertext Preprocessor.",
    "POS"  : "Point of Sale.",
    "PPC"  : "Pay Per Click.",
    "PPL"  : "Pay Per Lead.",
    "PPV"  : "Pay Per View.",
    "PR"   : "PageRank.",
    "PSLV" : "Polar Satellite Launch Vehicle.",
    "PV"   : "Page Views.",
    "PWD"  : "Public Works Department.",
    "QA"   : "Quality Assurance.",
    "QoQ"  : "Quarter-over-Quarter.",
    "QTD"  : "Quarter-to-Date.",
    "QR Code" : "Quick Response Code.",
    "QS"   : "Quality Score.",
    "RAC"  : "Reservation Against Cancellation.",
    "RAD"  : "Rapid Application Development.",
    "REST" : "Representational State Transfer .",
    "RFI"  : "Request For Information.",
    "RFP"  : "Request For Proposal.",
    "RfQ"  : "Request for Quotation.",
    "ROFL" : "Rolling On Floor Laughing.",
    "ROI"  : "Return On Investment.",
    "RON"  : "Run Of Network.",
    "ROR"  : "Ruby On Rails.", 
    "ROS"  : "Run Of Site.",
    "RSS"  : "Really Simple Syndication.",
    "RT"   : "Re Tweet.",
    "RTB"  : "Real Time Bidding.",
    "RTD"  : "Real Time Data.",
    "S2S"  : "Server to Server.",
    "SAARC": "South Asian Association for Regional Cooperation.",
    "SaaS" : "Software as a Service.",
    "SEB"  : "State Electricity Board.",
    "SEBI" : "Securities Exchange Board of India.",
    "SEM"  : "Search Engine Marketing.",
    "SENSEX": "Stock Exchange Sensitive Index.",
    "SEO"  : "Search Engine Optimization.",
    "SERP" : "Search Engine Results Page.",
    "SFTP" : "Secure FTP.",
    "SIM"  : "Subscriber Identity Module.",
    "SLA"  : "Service Level Agreement.",
    "SM"   : "Social Media.",
    "SME"  : "Small / Medium Enterprise.",
    "SMM"  : "Social Media Marketing.",
    "SMO"  : "Social Media Optimization.",
    "SMP"  : "Social Media Platform.",
    "SMS"  : "Short Message Service.",
    "SOAP" : "Small Objects Access Protocol.", 
    "SOV"  : "Share of Voice.",
    "SOW"  : "Statement of Work.",
    "SPCB" : "State Pollution Control Boards.",
    "SSA"  : "The Social Security Administration.",
    "SSH"  : "Secure Shell.",
    "SSL"  : "Secure Sockets Layer.",
    "SSP"  : "Supply-Side Platform.",
    "SWOT" : "Strengths, Weaknesses, Opportunities, Threats.",
    "TLD"  : "Top Level Domain.",
    "gTLD" : "Generic TLD.",
    "sTLD" : "Sponsored TLD.",
    "ccTLD": "Country Code TLD.",
    "vTLD" : "Vanity TLD.",
    "TOS"  : "Terms of Service.",
    "TNT"  : "Tuner Network Television.",
    "UCD"  : "User-Centric Design.",
    "UI"   : "User Interface.",
    "UGC"  : "User-Generated Content.",
    "URI"  : "Uniform Resource Indicator.",
    "URL"  : "Uniform Resource Locater.",
    "USP"  : "Unique Selling Proposition.",
    "UV"   : "Unique Visitor.",
    "UX"   : "User Experience.",
    "VOD"  : "Video on Demand.",
    "VOIP" : "Voice Over IP.",
    "VM"   : "Viral Marketing.",
    "WIFI" : "Wireless Fidelity.",
    "WIMAX": "Worldwide Interoperability for Microwave Access.",
    "WIMP" : "Windows Icons and Mouse Pointing.",
    "WOMM" : "Word of Mouth Marketing.",
    "WWW"  : "World Wide Web.",
    "WYSIWYG": "What You See Is What You Get.",
    "YOY"  : "Year On Year.",
    "YTD"  : "Year to Date.",
    "XML"  : "Extensible Markup Language."
};